#!/usr/bin/env python3
"""
train_rf_model.py

Trains a Random Forest classifier for 5-activity HAR (Human Activity Recognition):
  - Walking
  - Sitting / rest
  - Sleeping
  - Eating
  - Drinking

Uses pose features extracted from MediaPipe landmarks (15 features, matching activityDetection.js).

── Setup ───────────────────────────────────────────────────────────────────
  1. Collect training data using DataCollector.jsx
  2. Export sessions as har_session_*.json into a ./data folder
  3. Preprocess data by running:
     python preprocess_rf_data.py
     (This generates X.npy, y.npy from the har_session_*.json files)
  4. Train the model:
     python train_rf_model.py
  5. Model files will be saved in ./output/:
     - rf_model.pkl → copy to backend/app/models/
     - rf_model_stats.json → copy to backend/app/models/

── Output ──────────────────────────────────────────────────────────────────
  ./output/rf_model.pkl           → Binary Random Forest model
  ./output/rf_model_stats.json    → Normalization stats (mean, std)
"""

import numpy as np
import joblib
import json
import os
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# ── Configuration (must match activityDetection.js) ────────────────────────
NUM_FEATURES = 15
ACTIVITY_NAMES = [
    'Walking',
    'Sitting / rest',
    'Sleeping',
    'Eating',
    'Drinking'
]

# Random Forest hyperparameters
RF_N_ESTIMATORS = 100
RF_MAX_DEPTH = 15
RF_MIN_SAMPLES_SPLIT = 5
RF_MIN_SAMPLES_LEAF = 2
RF_RANDOM_STATE = 42

SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR / 'data'
OUTPUT_DIR = SCRIPT_DIR / 'output'

# ── Load preprocessed data ──────────────────────────────────────────────────
def load_data():
    """Load X.npy and y.npy generated by preprocess_rf_data.py"""
    X_path = DATA_DIR / 'X.npy'
    y_path = DATA_DIR / 'y.npy'
    
    if not X_path.exists() or not y_path.exists():
        raise FileNotFoundError(
            f"Missing data files. Please run preprocess_rf_data.py first.\n"
            f"  Expected: {X_path}\n"
            f"  Expected: {y_path}"
        )
    
    X = np.load(X_path)
    y = np.load(y_path)
    
    print(f"✓ Loaded X: {X.shape}, y: {y.shape}")
    return X, y

# ── Train Random Forest ────────────────────────────────────────────────────
def train_rf(X, y):
    """Train Random Forest classifier"""
    print("\n── Training Random Forest ──")
    print(f"  n_estimators: {RF_N_ESTIMATORS}")
    print(f"  max_depth: {RF_MAX_DEPTH}")
    print(f"  min_samples_split: {RF_MIN_SAMPLES_SPLIT}")
    print(f"  min_samples_leaf: {RF_MIN_SAMPLES_LEAF}")
    
    rf = RandomForestClassifier(
        n_estimators=RF_N_ESTIMATORS,
        max_depth=RF_MAX_DEPTH,
        min_samples_split=RF_MIN_SAMPLES_SPLIT,
        min_samples_leaf=RF_MIN_SAMPLES_LEAF,
        random_state=RF_RANDOM_STATE,
        n_jobs=-1,  # Use all available cores
        verbose=1
    )
    
    rf.fit(X, y)
    print(f"✓ Random Forest trained")
    return rf

# ── Evaluate model ────────────────────────────────────────────────────────
def evaluate_model(rf, X, y):
    """Evaluate Random Forest on the full dataset"""
    print("\n── Evaluating Random Forest ──")
    y_pred = rf.predict(X)
    accuracy = accuracy_score(y, y_pred)
    
    print(f"  Overall Accuracy: {accuracy:.4f}")
    print(f"\n  Classification Report:\n")
    print(classification_report(y, y_pred, target_names=ACTIVITY_NAMES))
    
    print(f"  Confusion Matrix:\n")
    cm = confusion_matrix(y, y_pred)
    print(cm)
    
    # Feature importance
    print(f"\n  Feature Importance (top 5):")
    feature_names = [
        "shoulder_angle", "elbow_angle", "hip_angle", "knee_angle", "ankle_angle",
        "arm_raise_left", "arm_raise_right", "hand_to_face", "hand_to_mouth",
        "arm_velocity", "leg_velocity", "torso_lean", "body_symmetry",
        "arm_spread", "hand_height"
    ]
    importances = rf.feature_importances_
    for i, importance in sorted(enumerate(importances), key=lambda x: x[1], reverse=True)[:5]:
        print(f"    {feature_names[i] if i < len(feature_names) else f'feature_{i}'}: {importance:.4f}")
    
    return accuracy

# ── Compute and save normalization stats ────────────────────────────────────
def save_stats(X):
    """Compute and save normalization stats (mean, std)"""
    mean = np.mean(X, axis=0).tolist()
    std = np.std(X, axis=0).tolist()
    
    stats = {
        'mean': mean,
        'std': std,
        'num_features': len(mean),
        'activity_names': ACTIVITY_NAMES
    }
    
    stats_path = OUTPUT_DIR / 'rf_model_stats.json'
    with open(stats_path, 'w') as f:
        json.dump(stats, f, indent=2)
    
    print(f"✓ Saved stats to {stats_path}")
    return stats

# ── Save model ────────────────────────────────────────────────────────────
def save_model(rf, output_dir):
    """Save Random Forest model using joblib"""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    model_path = output_dir / 'rf_model.pkl'
    joblib.dump(rf, model_path, compress=3)
    
    print(f"✓ Saved model to {model_path}")
    return model_path

# ── Main ────────────────────────────────────────────────────────────────────
def main():
    print("=" * 80)
    print("Random Forest HAR Model Training")
    print("=" * 80)
    
    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Load data
    X, y = load_data()
    
    # Train
    rf = train_rf(X, y)
    
    # Evaluate
    evaluate_model(rf, X, y)
    
    # Save stats
    save_stats(X)
    
    # Save model
    save_model(rf, OUTPUT_DIR)
    
    print("\n" + "=" * 80)
    print("✓ Training complete!")
    print("=" * 80)
    print(f"\nNext steps:")
    print(f"  1. Copy output/rf_model.pkl to backend/app/models/")
    print(f"  2. Copy output/rf_model_stats.json to backend/app/models/")
    print(f"  3. Restart the backend server")
    print(f"  4. The frontend will use the /api/activity/predict-rf endpoint")

if __name__ == '__main__':
    main()
